name = "argocd-image-updater"
type = "cli"

[platform.linux]
download-file = "argocd-image-updater-linux_{arch}"
checksum-file = "release-v{version}.sha256"

[platform.macos]
download-file = "argocd-image-updater-darwin_{arch}"
checksum-file = "release-v{version}.sha256"

[platform.windows]
download-file = "argocd-image-updater-win64.exe"
checksum-file = "release-v{version}.sha256"

[install]
download-url = "https://github.com/argoproj-labs/argocd-image-updater/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/argoproj-labs/argocd-image-updater/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.argocd-image-updater]
primary = true

[resolve]
git-url = "https://github.com/argoproj-labs/argocd-image-updater"
version-pattern = '^v(\d+\.\d+\.\d+)$'
