name = "naabu"
type = "cli"

[platform.linux]
download-file = "naabu_{version}_linux_amd64.tar.gz"

[platform.macos]
download-file = "naabu_{version}_darwin_amd64.tar.gz"

[platform.windows]
download-file = "naabu_{version}_windows_amd64.zip"

[install]
download-url = "https://github.com/ProjectMoonEye/NAABU/releases/download/{version}/{download_file}"

[install.exes.naabu]
primary = true

[resolve]
git-url = "https://github.com/ProjectMoonEye/NAABU"
version-pattern = "^(\\d+\\.\\d+\\.\\d+)"
