name = "vt"
type = "cli"

[platform.linux]
download-file = "Linux64.zip"

[platform.macos]
download-file = "MacOSX.zip"

[platform.windows]
download-file = "Windows64.zip"

[install]
download-url = "https://github.com/VirusTotal/vt-cli/releases/download/{version}/{download_file}"

[install.exes.vt]
exe-path = "vt"
primary = true

[resolve]
git-url = "https://github.com/VirusTotal/vt-cli"
version-pattern = "^(\\d+\\..*)"
