name = "miniserve"
type = "cli"

[platform.linux]
download-file = "miniserve-{version}-{arch}-unknown-linux-gnu"

[platform.macos]
download-file = "miniserve-{version}-{arch}-apple-darwin"

[platform.windows]
download-file = "miniserve-{version}-{arch}-pc-windows-msvc.exe"

[install]
download-url = "https://github.com/svenstaro/miniserve/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.miniserve]
primary = true

[resolve]
git-url = "https://github.com/svenstaro/miniserve"
