name = "ninja"
type = "cli"

[platform.linux]
download-file = "ninja-linux.zip"

[platform.macos]
download-file = "ninja-mac.zip"

[platform.windows]
download-file = "ninja-win.zip"

[install]
download-url = "https://github.com/ninja-build/ninja/releases/download/v{version}/{download_file}"

[install.exes.ninja]
primary = true

[resolve]
git-url = "https://github.com/ninja-build/ninja"
version-pattern = '^v?(\d+\.\d+\.\d+)$'
