name = "kargo"
type = "cli"

[platform.linux]
download-file = "kargo-linux-{arch}"

[platform.macos]
download-file = "kargo-darwin-{arch}"

[platform.windows]
download-file = "kargo-windows-{arch}.exe"

[install]
download-url = "https://github.com/akuity/kargo/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.kargo]
primary = true

[resolve]
git-url = "https://github.com/akuity/kargo"
version-pattern = '^v(\d+\.\d+\.\d+)$'
