name = "bandwhich"
type = "cli"

[platform.linux]
download-file = "bandwhich-v{version}-{arch}-unknown-linux-gnu.tar.gz"

[platform.macos]
download-file = "bandwhich-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
download-file = "bandwhich-v{version}-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/imsnif/bandwhich/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.bandwhich]
primary = true

[resolve]
git-url = "https://github.com/imsnif/bandwhich"
