name = "yq"
type = "cli"

[platform.linux]
download-file = "yq_linux_{arch}"

[platform.macos]
download-file = "yq_darwin_{arch}"

[platform.windows]
download-file = "yq_windows_{arch}.exe"

[install]
download-url = "https://github.com/mikefarah/yq/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.yq]
primary = true

[resolve]
git-url = "https://github.com/mikefarah/yq"
