name = "longhornctl"
type = "cli"

[platform.linux]
download-file = "longhornctl-linux-{arch}"
checksum-file = "longhornctl-linux-{arch}.sha256"

[platform.macos]
download-file = "longhornctl-darwin-{arch}"
checksum-file = "longhornctl-darwin-{arch}.sha256"

[install]
download-url = "https://github.com/longhorn/cli/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/longhorn/cli/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.longhornctl]
primary = true

[resolve]
git-url = "https://github.com/longhorn/cli"
version-pattern = '^v(\d+\.\d+\.\d+)$'
