name = "difft"
type = "cli"

[platform.linux]
download-file = "difft-{arch}-unknown-linux-gnu.tar.gz"

[platform.macos]
download-file = "difft-{arch}-apple-darwin.tar.gz"

[platform.windows]
download-file = "difft-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/Wilfred/difftastic/releases/download/{version}/{download_file}"
exe = "difft"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.difft]
primary = true

[resolve]
git-url = "https://github.com/Wilfred/difftastic"
version-pattern = "^(\\d+\\.\\d+\\.\\d+)"
