name = "alterx"
type = "cli"

[platform.linux]
download-file = "alterx_{version}_linux_amd64.tar.gz"

[platform.macos]
download-file = "alterx_{version}_darwin_amd64.tar.gz"

[platform.windows]
download-file = "alterx_{version}_windows_amd64.zip"

[install]
download-url = "https://github.com/projectdiscovery/alterx/releases/download/{version}/{download_file}"

[install.exes.alterx]
primary = true

[resolve]
git-url = "https://github.com/projectdiscovery/alterx"
version-pattern = "^(\\d+\\.\\d+\\.\\d+)"
