name = "tree-sitter"
type = "cli"

[platform.linux]
download-file = "tree-sitter-linux-{arch}.gz"
exe-path = "tree-sitter-linux-{arch}"

[platform.macos]
download-file = "tree-sitter-macos-{arch}.gz"
exe-path = "tree-sitter-macos-{arch}"

[platform.windows]
download-file = "tree-sitter-windows-{arch}.gz"
exe-path = "tree-sitter-windows-{arch}.exe"

[install]
download-url = "https://github.com/tree-sitter/tree-sitter/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x64"

[install.exes.tree-sitter]
primary = true

[resolve]
git-url = "https://github.com/tree-sitter/tree-sitter"
version-pattern = '^v(\d+\.\d+\.\d+)$'
