name = "massdns"
type = "cli"

[platform.linux]
download-file = "massdns_{version}_linux_amd64.tar.gz"

[platform.macos]
download-file = "massdns_{version}_darwin_amd64.tar.gz"

[install]
download-url = "https://github.com/blechschmidt/massdns/releases/download/v{version}/{download_file}"

[install.exes.massdns]
primary = true

[resolve]
git-url = "https://github.com/blechschmidt/massdns"
version-pattern = "^v?(\\d+\\.\\d+\\.\\d+)"
