name = "shfmt"
type = "cli"

[platform.linux]
download-file = "shfmt_v{version}_linux_{arch}"

[platform.macos]
download-file = "shfmt_v{version}_darwin_{arch}"

[platform.windows]
download-file = "shfmt_v{version}_windows_{arch}.exe"

[install]
download-url = "https://github.com/mvdan/sh/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.shfmt]
primary = true

[resolve]
git-url = "https://github.com/mvdan/sh"
