name = "sentry-cli"
type = "cli"

[platform.linux]
download-file = "sentry-cli-Linux-{arch}"

[platform.macos]
download-file = "sentry-cli-Darwin-{arch}"

[platform.windows]
download-file = "sentry-cli-Windows-{arch}.exe"

[install]
download-url = "https://github.com/getsentry/sentry-cli/releases/download/{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.sentry-cli]
primary = true

[resolve]
git-url = "https://github.com/getsentry/sentry-cli"
