name = "syft"
type = "cli"

[platform.linux]
download-file = "syft_{version}_linux_{arch}.tar.gz"
archive-prefix = ""

[platform.macos]
download-file = "syft_{version}_darwin_{arch}.tar.gz"
archive-prefix = ""

[platform.windows]
download-file = "syft_{version}_windows_{arch}.zip"
archive-prefix = ""

[install]
download-url = "https://github.com/anchore/syft/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.syft]
primary = true

[resolve]
git-url = "https://github.com/anchore/syft"
version-pattern = '^v(\d+\.\d+\.\d+)$'
