name = "pulumi"
type = "cli"

[metadata]

[resolve]
git-url = "https://github.com/pulumi/pulumi"

[platform.linux]
download-file = "pulumi-v{version}-linux-{arch}.tar.gz"
exe-path = "pulumi"

[platform.macos]
download-file = "pulumi-v{version}-darwin-{arch}.tar.gz"
exe-path = "pulumi"

[platform.windows]
download-file = "pulumi-v{version}-windows-{arch}.zip"
exe-path = "pulumi.exe"

[install]
download-url = "https://github.com/pulumi/pulumi/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x64"
