name = "bitwarden-cli"
type = "cli"

[platform.linux]
download-file = "bw-linux-{version}.zip"

[platform.macos]
download-file = "bw-macos-{version}.zip"

[platform.windows]
download-file = "bw-windows-{version}.zip"

[install]
download-url = "https://github.com/bitwarden/cli/releases/download/v{version}/{download_file}"

[install.exes.bw]
primary = true

[resolve]
git-url = "https://github.com/bitwarden/cli"
