name = "newrelic"
type = "cli"

[platform.linux]
download-file = "newrelic-cli_{version}_Linux_{arch}.tar.gz"
checksum-file = "newrelic-cli_{version}_checksums.txt"

[platform.macos]
download-file = "newrelic-cli_{version}_Darwin_{arch}.tar.gz"
checksum-file = "newrelic-cli_{version}_checksums.txt"

[platform.windows]
download-file = "newrelic-cli_{version}_Windows_{arch}.zip"
checksum-file = "newrelic-cli_{version}_checksums.txt"

[install]
download-url = "https://github.com/newrelic/newrelic-cli/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/newrelic/newrelic-cli/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x86_64"

[install.exes.newrelic]
primary = true

[resolve]
git-url = "https://github.com/newrelic/newrelic-cli"
