name = "gum"
type = "cli"

[platform.linux]
download-file = "gum_{version}_Linux_{arch}.tar.gz"
archive-prefix = ""

[platform.macos]
download-file = "gum_{version}_Darwin_{arch}.tar.gz"
archive-prefix = ""

[platform.windows]
download-file = "gum_{version}_Windows_{arch}.zip"
archive-prefix = ""

[install]
download-url = "https://github.com/charmbracelet/gum/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x86_64"

[install.exes.gum]
primary = true

[resolve]
git-url = "https://github.com/charmbracelet/gum"
