name = "k3d"
type = "cli"

[platform.linux]
download-file = "k3d-linux-{arch}"

[platform.macos]
download-file = "k3d-darwin-{arch}"

[platform.windows]
download-file = "k3d-windows-{arch}.exe"

[install]
download-url = "https://github.com/k3d-io/k3d/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.k3d]
primary = true

[resolve]
git-url = "https://github.com/k3d-io/k3d"
version-pattern = '^v(\d+\.\d+\.\d+)$'
