name = "rclone"
type = "cli"

[platform.linux]
download-file = "rclone-v{version}-linux-{arch}.zip"
archive-prefix = "rclone-v{version}-linux-{arch}"

[platform.macos]
download-file = "rclone-v{version}-osx-{arch}.zip"
archive-prefix = "rclone-v{version}-osx-{arch}"

[platform.windows]
download-file = "rclone-v{version}-windows-{arch}.zip"
archive-prefix = "rclone-v{version}-windows-{arch}"

[install]
download-url = "https://github.com/rclone/rclone/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.rclone]
primary = true

[resolve]
git-url = "https://github.com/rclone/rclone"
version-pattern = '^v(\d+\.\d+\.\d+)$'
