name = "harbor"
type = "cli"

[platform.linux]
download-file = "harbor-cli_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "harbor-cli_{version}_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "harbor-cli_{version}_windows_{arch}.zip"

[install]
download-url = "https://github.com/goharbor/harbor-cli/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[install.exes.harbor]
exe-path = "harbor-cli"
primary = true

[resolve]
git-url = "https://github.com/goharbor/harbor-cli"
version-pattern = '^v(\d+\.\d+\.\d+)$'
