name = "dnstraceroute"
type = "cli"

[platform.linux]
download-file = "dnstraceroute_{version}_linux_amd64.tar.gz"

[install]
download-url = "https://github.com/habbie/dnstraceroute/releases/download/v{version}/{download_file}"

[install.exes.dnstraceroute]
primary = true

[resolve]
git-url = "https://github.com/habbie/dnstraceroute"
version-pattern = "^v(\\d+\\.\\d+\\.\\d+)"
