name = "puredns"
type = "cli"

[platform.linux]
download-file = "puredns_{version}_linux_x86_64.tar.gz"

[platform.macos]
download-file = "puredns_{version}_macos_x86_64.tar.gz"

[platform.windows]
download-file = "puredns_{version}_windows_x86_64.zip"

[install]
download-url = "https://github.com/d3wardoo/puredns/releases/download/{version}/{download_file}"

[install.exes.puredns]
primary = true

[resolve]
git-url = "https://github.com/d3wardoo/puredns"
version-pattern = "^(\\d+\\.\\d+\\.\\d+)"
