name = "dnsx"
type = "cli"

[platform.linux]
download-file = "dnsx_{version}_linux_amd64.tar.gz"

[platform.macos]
download-file = "dnsx_{version}_darwin_amd64.tar.gz"

[platform.windows]
download-file = "dnsx_{version}_windows_amd64.zip"

[install]
download-url = "https://github.com/khastandx/dnsx/releases/download/{version}/{download_file}"

[install.exes.dnsx]
primary = true

[resolve]
git-url = "https://github.com/khastandx/dnsx"
version-pattern = "^(\\d+\\.\\d+\\.\\d+)"
