name = "procs"
type = "cli"

[platform.linux]
download-file = "procs-v{version}-{arch}-linux.zip"

[platform.macos]
download-file = "procs-v{version}-{arch}-mac.zip"

[platform.windows]
download-file = "procs-v{version}-{arch}-windows.zip"

[install]
download-url = "https://github.com/dalance/procs/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.procs]
primary = true

[resolve]
git-url = "https://github.com/dalance/procs"
version-pattern = '^v(\d+\.\d+\.\d+)$'
