name = "dalfox"
type = "cli"

[platform.linux]
download-file = "dalfox-v{version}-linux-{arch}.tar.gz"
checksum-file = "dalfox-v{version}-linux-{arch}.tar.gz.sha256"

[platform.macos]
download-file = "dalfox-v{version}-macos-{arch}.tar.gz"
checksum-file = "dalfox-v{version}-macos-{arch}.tar.gz.sha256"

[platform.windows]
download-file = "dalfox-v{version}-windows-{arch}.zip"
checksum-file = "dalfox-v{version}-windows-{arch}.zip.sha256"

[install]
download-url = "https://github.com/hahwul/dalfox/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/hahwul/dalfox/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.dalfox]
primary = true

[resolve]
git-url = "https://github.com/hahwul/dalfox"
version-pattern = '^v((?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+))$'
