name = "fd"
type = "cli"

[platform.linux]
download-file = "fd-v{version}-{arch}-unknown-linux-gnu.tar.gz"
archive-prefix = "fd-v{version}-{arch}-unknown-linux-gnu"

[platform.macos]
download-file = "fd-v{version}-{arch}-apple-darwin.tar.gz"
archive-prefix = "fd-v{version}-{arch}-apple-darwin"

[platform.windows]
download-file = "fd-v{version}-{arch}-pc-windows-msvc.zip"
archive-prefix = "fd-v{version}-{arch}-pc-windows-msvc"

[install]
download-url = "https://github.com/sharkdp/fd/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.exes.fd]
primary = true

[resolve]
git-url = "https://github.com/sharkdp/fd"
version-pattern = '^v(\d+\.\d+\.\d+)$'
