name = "actionlint"
type = "cli"

[platform.linux]
download-file = "actionlint_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "actionlint_{version}_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "actionlint_{version}_windows_{arch}.zip"

[install]
download-url = "https://github.com/rhysd/actionlint/releases/download/v{version}/{download_file}"

[install.arch]
x86_64 = "amd64"
arm64 = "arm64"
aarch64 = "arm64"

[install.exes.actionlint]
primary = true

[resolve]
git-url = "https://github.com/rhysd/actionlint"
version-pattern = '^v?(\d+\.\d+\.\d+)$'
